export default {
    AUTH_LOGIN: '/auth/login',
    AUTH_VERIFY: '/auth/verify',
    AUTH_LOGOUT: '/auth/logout',
    REDIRECT_RULES: '/mapping/redirects',
    INGRESS_RULES: '/mapping/ingresses',
    RESTRICTED_PORTS: '/mapping/ingresses/restricted-ports',
    DOMAINS: '/domains',
    DOMAIN_NAMES: '/domains/shortlist',
    GIT_CREDENTIALS: '/git/credentials',
    VOLUMES: '/volumes',
    SERVICE_NAMES: '/applications/servicenames',
    APPLICATIONS: '/applications',
    APPLICATIONS_SUMMARY: '/applications/summary',
    APPLICATION_SERVICE_NAME_AVAILABILITY: '/applications/availiblity/service_name',
}