export default {
  "none": "gray",
  "issuing": "yellow",
  "issued": "green",
  "applied": "green",
  "pending": "yellow",
  "building_image": "yellow",
  "building_image_queued": "yellow",
  "building_image_completed": "green",
  "building_image_failed": "red",
  "deploying_pending": "yellow",
  "deploying": "yellow",
  "deploying_queued": "yellow",
  "deploying_failed": "red",
  "delete_pending": "red",
  "running": "green",
  "stopped": "gray",
  "failed": "red",
  "redeploy_pending": "yellow",
}